title: Azure Data Engineer Associate Questions
description: These are memory based questions for the assessment conducted on Jul 2023. Multiple questions mentioned here can be a part of one question. I have remembered the questions best possible. 
theme: jekyll-theme-cayman
